# Generated by Django 5.1.7 on 2025-03-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField()),
            ],
        ),
    ]
